[default]
duration = "30m"
mode = "center"
sorting = "ascending"

[eDP-1]
path = "/home/adrian/.config/backgrounds/logo_w600.png"
# path = "/home/adrian/.config/backgrounds/bluemountain.jpg"

# ["BNQ BenQ RD280UA JBR0003701Q"]
# path = "/home/adrian/.config/backgrounds/bluemountain.jpg"

[any]
path = "/home/adrian/.config/backgrounds"

