-- Generated by nwg-displays on 2026-05-31 at 12:13:47. Do not edit manually.

hl.monitor({
    output = "desc:Chimei Innolux Corporation 0x140A",
    mode = "1920x1080@60.0",
    position = "3072x478",
    scale = 1.0
})
hl.monitor({
    output = "desc:BNQ BenQ RD280UA JBR0003701Q",
    mode = "3840x2560@59.98",
    position = "0x0",
    scale = 1.25
})
